ColumnsToRemove:
  # Columns that has null value more than 70%
  NullColumns:
    - 'CANCELLATION_REASON'
    - "AIR_SYSTEM_DELAY"
    - "SECURITY_DELAY"
    - "AIRLINE_DELAY"
    - "LATE_AIRCRAFT_DELAY"
    - "WEATHER_DELAY"
  
  # Id Columns
  UniqueColumns:
    - "FLIGHT_NUMBER" 
    - "TAIL_NUMBER" 

  # Columns with one value for all the rows
  NoValueColumns:
    - "CANCELLED"
    - "DIVERTED"
    - "YEAR"
  
  # conclosions from the target
  Targets:
    - "ELAPSED_TIME"
    - "AIR_TIME"
    - "WHEELS_ON"
    - "WHEELS_OFF"
    - "TAXI_IN" 
    - "TAXI_OUT"
    - "ARRIVAL_TIME"
  
  # Columns representing time information
  TimeColumns:
    - "SCHEDULED_ARRIVAL"
    - "SCHEDULED_DEPARTURE"
    - "DEPARTURE_TIME"
    - "ARRIVAL_TIME"

# Columns To remove null from
CleaningColumns:
  - "DEPARTURE_DELAY"
  - "ARRIVAL_DELAY"

Target: "ARRIVAL_DELAY"

FeatureEngCols:
  OheCols:
    - "AIRLINE"

  LabelCols:
    - "ORIGIN_AIRPORT"
    - "DESTINATION_AIRPORT"
  
  CyclicCols:
    - "MONTH"
    - "DAY"
    - "DAY_OF_WEEK"
  
  ScaleCols:
    - "SCHEDULED_TIME"
    - "DEPARTURE_DELAY"
    - "DISTANCE"

ProcessingPipelinePath: "../artifacts/pipelines/"

modelParams:
  hidden_units: [256, 128, 64]
  dropout_rates: [0.0, 0.05, 0.05]
  activation: swish
  batch_norm: true
  learning_rate: 0.0003

compileParams:
  optimizer:
    type: "Adam"
    lr: 0.0003

  loss: "mae"
  metrics:
    - "mse"
    - "mae"

fitParams:
  epochs: 30
  batch_size: 1024

ModelSavePath: "../artifacts/models/"

ResultsPath: "../artifacts/results"